// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: sayhi.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SayhiServiceClient is the client API for SayhiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SayhiServiceClient interface {
	Sayhi(ctx context.Context, in *SayhiRequest, opts ...grpc.CallOption) (*SayhiResponse, error)
}

type sayhiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSayhiServiceClient(cc grpc.ClientConnInterface) SayhiServiceClient {
	return &sayhiServiceClient{cc}
}

func (c *sayhiServiceClient) Sayhi(ctx context.Context, in *SayhiRequest, opts ...grpc.CallOption) (*SayhiResponse, error) {
	out := new(SayhiResponse)
	err := c.cc.Invoke(ctx, "/sayhi.SayhiService/Sayhi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SayhiServiceServer is the server API for SayhiService service.
// All implementations must embed UnimplementedSayhiServiceServer
// for forward compatibility
type SayhiServiceServer interface {
	Sayhi(context.Context, *SayhiRequest) (*SayhiResponse, error)
	mustEmbedUnimplementedSayhiServiceServer()
}

// UnimplementedSayhiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSayhiServiceServer struct {
}

func (UnimplementedSayhiServiceServer) Sayhi(context.Context, *SayhiRequest) (*SayhiResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sayhi not implemented")
}
func (UnimplementedSayhiServiceServer) mustEmbedUnimplementedSayhiServiceServer() {}

// UnsafeSayhiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SayhiServiceServer will
// result in compilation errors.
type UnsafeSayhiServiceServer interface {
	mustEmbedUnimplementedSayhiServiceServer()
}

func RegisterSayhiServiceServer(s grpc.ServiceRegistrar, srv SayhiServiceServer) {
	s.RegisterService(&SayhiService_ServiceDesc, srv)
}

func _SayhiService_Sayhi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayhiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SayhiServiceServer).Sayhi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sayhi.SayhiService/Sayhi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SayhiServiceServer).Sayhi(ctx, req.(*SayhiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SayhiService_ServiceDesc is the grpc.ServiceDesc for SayhiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SayhiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sayhi.SayhiService",
	HandlerType: (*SayhiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sayhi",
			Handler:    _SayhiService_Sayhi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sayhi.proto",
}
