// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.13.0
// source: sayhi.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SayhiRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName string `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
}

func (x *SayhiRequest) Reset() {
	*x = SayhiRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sayhi_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayhiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayhiRequest) ProtoMessage() {}

func (x *SayhiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sayhi_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayhiRequest.ProtoReflect.Descriptor instead.
func (*SayhiRequest) Descriptor() ([]byte, []int) {
	return file_sayhi_proto_rawDescGZIP(), []int{0}
}

func (x *SayhiRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

type SayhiResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SayhiResponse) Reset() {
	*x = SayhiResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sayhi_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SayhiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SayhiResponse) ProtoMessage() {}

func (x *SayhiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sayhi_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SayhiResponse.ProtoReflect.Descriptor instead.
func (*SayhiResponse) Descriptor() ([]byte, []int) {
	return file_sayhi_proto_rawDescGZIP(), []int{1}
}

func (x *SayhiResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_sayhi_proto protoreflect.FileDescriptor

var file_sayhi_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x61, 0x79, 0x68, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x61, 0x79, 0x68, 0x69, 0x22, 0x2d, 0x0a, 0x0c, 0x53, 0x61, 0x79, 0x68, 0x69, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x69, 0x72, 0x73, 0x74, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e,
	0x61, 0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0d, 0x53, 0x61, 0x79, 0x68, 0x69, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x42, 0x0a, 0x0c,
	0x53, 0x61, 0x79, 0x68, 0x69, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x32, 0x0a, 0x05,
	0x53, 0x61, 0x79, 0x68, 0x69, 0x12, 0x13, 0x2e, 0x73, 0x61, 0x79, 0x68, 0x69, 0x2e, 0x53, 0x61,
	0x79, 0x68, 0x69, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14, 0x2e, 0x73, 0x61, 0x79,
	0x68, 0x69, 0x2e, 0x53, 0x61, 0x79, 0x68, 0x69, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x42, 0x33, 0x5a, 0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69,
	0x75, 0x67, 0x6d, 0x61, 0x6c, 0x69, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x67, 0x72,
	0x70, 0x63, 0x2d, 0x63, 0x6f, 0x75, 0x72, 0x73, 0x65, 0x2f, 0x73, 0x61, 0x79, 0x68, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sayhi_proto_rawDescOnce sync.Once
	file_sayhi_proto_rawDescData = file_sayhi_proto_rawDesc
)

func file_sayhi_proto_rawDescGZIP() []byte {
	file_sayhi_proto_rawDescOnce.Do(func() {
		file_sayhi_proto_rawDescData = protoimpl.X.CompressGZIP(file_sayhi_proto_rawDescData)
	})
	return file_sayhi_proto_rawDescData
}

var file_sayhi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sayhi_proto_goTypes = []interface{}{
	(*SayhiRequest)(nil),  // 0: sayhi.SayhiRequest
	(*SayhiResponse)(nil), // 1: sayhi.SayhiResponse
}
var file_sayhi_proto_depIdxs = []int32{
	0, // 0: sayhi.SayhiService.Sayhi:input_type -> sayhi.SayhiRequest
	1, // 1: sayhi.SayhiService.Sayhi:output_type -> sayhi.SayhiResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sayhi_proto_init() }
func file_sayhi_proto_init() {
	if File_sayhi_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sayhi_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayhiRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sayhi_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SayhiResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sayhi_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sayhi_proto_goTypes,
		DependencyIndexes: file_sayhi_proto_depIdxs,
		MessageInfos:      file_sayhi_proto_msgTypes,
	}.Build()
	File_sayhi_proto = out.File
	file_sayhi_proto_rawDesc = nil
	file_sayhi_proto_goTypes = nil
	file_sayhi_proto_depIdxs = nil
}
